### ISSUE TITLE
document wont push from Mashbill

### ISSUE THREAD

**Issue by emilydmoses** [CivilWarGovernorsOfKentucky/Documents#1]
xml/KYR-0001-021-0030.xml

Error on screen when selecting "Update Document". error does not appear in the log. TEI update does not appear in github.

**Comment by emilydmoses** [comment]
KYR-0001-004-0996
KYR-0001-004-0931
KYR-0001-004-0941
![Annotation Corrupts TEI](https://user-images.githubusercontent.com/40738811/59300967-805e7800-8c5e-11e9-83e7-b5688417080f.JPG)

Error on screen when selecting "Update Document". error does not appear in the log. TEI update does not appear in github.

**Comment by emilydmoses** [comment]
KYR-0001-009-0055

**Comment by haywoodsarahe** [comment]
KYR-0002-222-0033, 0036, 0037, 0038, 0039

Error on screen when selecting "Mark Document Complete." Error does not appear in the log.

**Comment by haywoodsarahe** [comment]
KYR-0002-222-0027. 0028, 0029, 0030.
KYR-0002-022-0087, 0089.

Error on screen when selecting "Mark Document Complete." Error does not appear in the log. Tags don't push. (KYR-0002-022-0088 seems similar and had no problem)

**Comment by cwelsko** [comment]
KYR-0001-004-1941

Similar to previous issues, when selecting "Mark Document Complete." Tags don't push.

**Comment by dthompsonKHS** [comment]
KYR-0002-022-0094, 0095.
Error on screen when selecting "Mark Document Complete." Error does not appear in the log. Tags don't push.

**Comment by dthompsonKHS** [comment]
KYR-0002-022-0106. Gave me an error message when selecting "Mark Document Complete." ...mark_complete/1463. Error does not appear in the log. Tags don't push.

**Comment by dthompsonKHS** [comment]
KYR-0002-022-0112. Error on screen when selecting "Mark Document Complete," last four digits of url in this pop-up message are 1471. Error does not appear in the log. Tags don't push.

**Comment by dthompsonKHS** [comment]
Judge of his county KYR-0002-022-0119 https://hyp.is/W6uvlt73EemSPj-NqZ4s4Q

**Comment by haywoodsarahe** [comment]
Mashbill error for KYR-0004-033-0002, KYR-0001-006-0066, KYR-0001-020-1708.
