### ISSUE TITLE
Document pushed but majority of entities not coded

### ISSUE THREAD

**Issue by dthompsonKHS** [CivilWarGovernorsOfKentucky/Documents#2]
KYR-0001-004-0051 had 13 entities and only 4 of them were coded (all those that were coded were in the body of the letter rather than listed in a column. Only one of the ones not coded had any special characters or treatments like underlining. They were, however, ones that were listed with line breaks. Normally this has not caused a problem. Most of the entities that do not get coded in other documents are ones with those special characters.

**Comment by haywoodsarahe** [comment]
KYR-0004-033-0009. The majority of these tags did not push when the document was completed. There was no mashbill error in the log. The errors in oxygen did not seem to be related to special formatting (like underlines, supers, etc.).
